spring.application.name=${SPRING_APPLICATION_NAME}

# AWS S3 Configuration
aws.s3.bucket.name=${AWS_S3_BUCKET_NAME}
aws.s3.region=${AWS_S3_REGION}
aws.s3.access.key=${AWS_S3_ACCESS_KEY_ID}
aws.s3.secret.access.key=${AWS_S3_SECRET_ACCESS_KEY}

# GCP Storage Configuration
gcp.storage.bucket.name=${GCP_BUCKET_NAME}
gcp.storage.project.id=${GCP_PROJECT_ID}
gcp.storage.credentials.json=${GCP_CREDENTIALS_JSON}