# The .env loader will set these as system properties
spring.application.name=${SPRING_APPLICATION_NAME:bucketadapter}
server.port=${SERVER_PORT:8080}

# Logging configuration
logging.level.com.example=DEBUG
logging.level.root=INFO

springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
