name: CI - Lint, Tests & Docker Build

on:
  pull_request:

jobs:
  build:
    name: Lint, Tests & Docker Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Run linter (Checkstyle)
        run: ./mvnw checkstyle:check

      - name: Run tests
        run: ./mvnw test

      - name: Build Docker image
        if: github.base_ref == 'develop' || github.base_ref == 'main' # Only build on develop or main branches
        run: |
          docker build \
            --file Dockerfile \
            --tag bucket-adapter:latest \
            --progress=plain \
            .
