name: CI - Lint, Tests & Docker Build

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Lint, Tests & Docker Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Run linter (Checkstyle)
        run: ./mvnw checkstyle:check
        continue-on-error: true

      - name: Run tests
        run: ./mvnw test

      - name: Create .env for CI
        run: |
          cat <<EOF > .env
          AWS_BUCKET_NAME=${{ secrets.AWS_BUCKET_NAME }}
          AWS_REGION=${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }}
          GCP_BUCKET_NAME=${{ secrets.GCP_BUCKET_NAME }}
          GCP_CREDENTIALS_JSON='${{ secrets.GCP_CREDENTIALS_JSON }}'
          SPRING_APPLICATION_NAME='${{ secrets.APP_NAME }}'
          SERVER_PORT='${{ secrets.SERVER_PORT }}'
          PROVIDER_IMPL='${{ secrets.PROVIDER_IMPL }}'
          EOF

      - name: Build Docker image
        if: github.base_ref == 'develop' || github.base_ref == 'main'
        run: |
          docker build \
            --file Dockerfile \
            --tag bucket-adapter:latest \
            .
